/**
 * Marketing-site config in one place.
 *
 * App Store: LIVE since 15 Aug 2026. Every "get the app" CTA reads from here,
 * so flipping `available` un-inerts all of them at once — `AppStoreCta` stops
 * rendering a `<span aria-disabled>` and renders a real `<a>`, which is what
 * lets `reportStoreClick()` fire at all.
 *
 * `url` is deliberately storefront-agnostic rather than the `/gb/…` URL App
 * Store Connect shows in the UI: Apple geo-redirects to the visitor's own
 * storefront, and the app ships in 175 territories, so a hardcoded `/gb/`
 * would send everyone to the UK store.
 *
 * The `/app/apple-store/id<id>` path is the exact shape App Store Connect's
 * own "Generate a Campaign Link" dialog produces, so campaign-decorated CTAs
 * are byte-identical to a link Apple generated itself.
 *
 * `appId` also unlocks a live rating badge via Apple's public iTunes Lookup API
 * (https://itunes.apple.com/lookup?id=<appId> → averageUserRating), which can
 * then replace the static proof chips in the hero.
 */
export const appStore = {
  available: true as boolean,
  url: "https://apps.apple.com/app/apple-store/id6755091280" as string | null,
  appId: "6755091280" as string | null,
};

/**
 * Play Store: LIVE since 31 Aug 2026. Every Android CTA and the `/g/<slug>`
 * QR redirect reads from here, so this is the single launch switch.
 *
 * Flipping it also retires the Android notify list on Home and re-points the
 * /support Android answer and the `/g/<slug>` edge redirect, all from here.
 */
export const playStore = {
  available: true as boolean,
  url: "https://play.google.com/store/apps/details?id=com.bradleyevans96.persistence" as
    | string
    | null,
};

/**
 * ONE predicate per store, and the only thing any page, gate or CTA should ask.
 *
 * Both store configs carry TWO fields, and a CTA cannot render without both —
 * `available` says we intend to link, `url` is what it links to. Reading only
 * `available` is what let a half-state produce an incoherent page: setting
 * `playStore.available = true` and leaving `url` null (the obvious one-line
 * edit on Android launch day, and exactly what Home's own comment invited)
 * removed the Android notify list, left the Play button reading "Coming soon",
 * and had /support announce the app was on Play — no route to it from anywhere.
 * The App Store side had the identical shape with `url` nulled.
 *
 * So prose, gating and CTAs all read this, and a half-state is simply the
 * not-live state rather than a third, incoherent one.
 */
export const appStoreLive = (): boolean =>
  appStore.available && appStore.url !== null;

export const playStoreLive = (): boolean =>
  playStore.available && playStore.url !== null;

/**
 * Apple's Provider Token — the numeric id of our App Store Connect provider.
 * Verified 15 Aug 2026 against a link generated by App Store Connect itself
 * (Analytics → Acquisition → Campaigns → Generate a Campaign Link):
 *
 *   https://apps.apple.com/app/apple-store/id6755091280?pt=128225445&ct=<name>&mt=8
 *
 * ⚠️ `pt` is NOT a per-campaign label. It identifies the provider and is the
 * same value on every campaign link we will ever issue; the per-campaign part
 * is `ct` alone. This previously held descriptive strings (`uon_campus`,
 * `flyer_print`, `qr`), which App Analytics would not have attributed — and
 * because printed QR codes are fixed for the life of the print run, that would
 * have been unrecoverable once 5,000 leaflets shipped.
 */
export const APPLE_PROVIDER_TOKEN = "128225445";

/** Apple's media type for iOS apps; ASC includes it on every campaign link. */
const APPLE_MEDIA_TYPE = "8";

/**
 * Per-campaign attribution tokens, keyed by the landing-route slug
 * (`/uon`, `/flyer`, `/qr/:slug`). `ct` is Apple's campaign token (surfaced in
 * App Analytics); `utm_source`/`utm_campaign` are the referrer params the Play
 * Console attributes installs by. `pt` is deliberately absent — see
 * {@link APPLE_PROVIDER_TOKEN}; `appStoreUrl` supplies it. Adding a new
 * printed/QR asset is one new entry here — no other code changes. `default` is
 * the fallback used by any `/qr/:slug` whose slug isn't (yet) a distinct entry
 * of its own.
 */
export interface Campaign {
  ct?: string;
  utm_source?: string;
  utm_campaign?: string;
}

export const CAMPAIGNS: Record<string, Campaign> = {
  // Print / physical assets. These slugs are encoded into artwork that is
  // fixed for the life of the print run — never rename or remove one.
  uon: { ct: "uon", utm_source: "uon", utm_campaign: "campus" },
  flyer: { ct: "flyer", utm_source: "flyer", utm_campaign: "print" },
  banner: { ct: "banner", utm_source: "banner", utm_campaign: "print" },

  // Social. `social` is the human-memorable one — spoken aloud, typed into
  // WhatsApp; the rest are pasted once into a bio field.
  //
  // Note what these do NOT do: Meta attributes on its own click id (`fbclid`)
  // and pixel cookies, and never reads `ct` or `utm_source`. These serve App
  // Store Connect, the Play Console and our own analytics_events. What helps
  // Meta is that the link lands on the marketing site at all, so the pixel can
  // fire — which is the reason none of these point straight at apps.apple.com.
  social: { ct: "social", utm_source: "social", utm_campaign: "launch" },
  // Paid Meta/Instagram placements. Distinct from `ig`, which is the ORGANIC
  // bio link — keeping them apart is what lets the founders'-offer ad spend be
  // read separately from the profile's own traffic.
  meta: { ct: "meta", utm_source: "meta", utm_campaign: "founders" },
  tt: { ct: "tt", utm_source: "tiktok", utm_campaign: "bio" },
  ig: { ct: "ig", utm_source: "instagram", utm_campaign: "bio" },
  li: { ct: "li", utm_source: "linkedin", utm_campaign: "bio" },

  default: { ct: "qr", utm_source: "qr", utm_campaign: "qr" },
};

function appendParams(
  baseUrl: string,
  params: Record<string, string | undefined>,
): string {
  const entries = Object.entries(params).filter(
    (entry): entry is [string, string] => Boolean(entry[1]),
  );
  if (entries.length === 0) return baseUrl;
  const search = new URLSearchParams(entries);
  const separator = baseUrl.includes("?") ? "&" : "?";
  return `${baseUrl}${separator}${search.toString()}`;
}

/**
 * App Store CTA URL. With a known `campaign` slug, produces the same
 * `?pt=…&ct=…&mt=8` triple App Store Connect's own campaign-link generator
 * emits; with no campaign, returns the bare store URL. Returns `null` when the
 * store isn't live yet (`appStore.url` is `null`) — there is nothing to link to
 * regardless of campaign.
 *
 * `pt` and `mt` are constants, not per-campaign values: only `ct` varies.
 */
export function appStoreUrl(campaign?: string): string | null {
  if (!appStore.url) return null;
  if (!campaign) return appStore.url;
  const c = CAMPAIGNS[campaign];
  if (!c?.ct) return appStore.url;
  return appendParams(appStore.url, {
    pt: APPLE_PROVIDER_TOKEN,
    ct: c.ct,
    mt: APPLE_MEDIA_TYPE,
  });
}

/**
 * Play Store CTA URL — see {@link appStoreUrl}. Google Play attributes installs
 * from one URL-encoded `referrer` parameter, so the campaign's UTM query string
 * is nested inside it rather than emitted as top-level `utm_*` parameters.
 * Returns `null` when `playStore.url` is `null`.
 */
export function playStoreUrl(campaign?: string): string | null {
  if (!playStore.url) return null;
  if (!campaign) return playStore.url;
  const c = CAMPAIGNS[campaign];
  if (!c) return playStore.url;
  const referrer = new URLSearchParams(
    Object.entries({
      utm_source: c.utm_source,
      utm_campaign: c.utm_campaign,
    }).filter((entry): entry is [string, string] => Boolean(entry[1])),
  ).toString();
  if (!referrer) return playStore.url;
  return appendParams(playStore.url, {
    referrer,
  });
}

/**
 * App Store / Play offer-code redemption URLs for the founders' rate.
 *
 * Read at CALL time, not module load, so a stage without them simply renders
 * no offer CTA — the same fail-quiet shape as the pixel id and the Turnstile
 * site key. Both are genuinely public: the redemption URL is what an ad would
 * link to.
 *
 * The offers themselves — price, duration, eligibility, redemption cap and
 * expiry — are configured in App Store Connect / the Play Console and are NOT
 * represented here. Nothing on this side can enforce or even read them, which
 * is why the CTA copy names no price: the figure Apple actually charges is the
 * nearest Apple tier, and it is read back from ASC before it appears anywhere.
 *
 * ⚠ iOS must not be switched on until one code has been redeemed end to end on
 * a fresh Apple ID and a `user_subscriptions` row confirmed server-side —
 * RevenueCat skips anonymous ids, so a redemption that never reaches our
 * database would be an invisible sale (MARKETING_BRIEF § 2, Lane B).
 */
export function storeOfferUrl(platform: "ios" | "android"): string | null {
  const raw =
    platform === "ios"
      ? import.meta.env.VITE_STORE_OFFER_IOS_URL
      : import.meta.env.VITE_STORE_OFFER_ANDROID_URL;
  return (raw ?? "").trim() || null;
}

/**
 * Campaign slugs whose landing page offers the store founders' rate.
 *
 * Cold ad traffic gets the offer; an organic visitor on `/` keeps the plain
 * store CTA. Deliberately an allow-list rather than "every campaign": the
 * printed slugs (`flyer`, `banner`, `uon`) are fixed for the life of a print
 * run and predate the offer, so quietly turning them into offer routes would
 * change what artwork already in the world means.
 */
export const STORE_OFFER_CAMPAIGNS: readonly string[] = ["meta"];

/**
 * Hero phone screenshot. Null → the pure-CSS app mock renders in the tilting
 * frame. When real screenshots are ready, drop the image in `public/` and set
 * this to its path (e.g. "/hero-screenshot.png", ideally a 9:19.5 portrait
 * capture) — it renders inside the same hover-tilt frame, no other changes.
 */
export const heroScreenshot: string | null = null;

/** Contact address — matches the live address used in the Privacy policy. */
export const CONTACT_EMAIL = "admin@evans-software-solutions.com";

export const TEAMS_MAILTO = `mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent(
  "Persistence for Teams",
)}`;

export const SUPPORT_MAILTO = `mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent(
  "Persistence support",
)}`;

export const COMPANY = "Evans Software Solutions Ltd";
export const COMPANY_URL = "https://evans-software-solutions.com";
