/**
 * Marketing-site config in one place.
 *
 * App Store: LIVE since 15 Aug 2026. Every "get the app" CTA reads from here,
 * so flipping `available` un-inerts all of them at once — `AppStoreCta` stops
 * rendering a `<span aria-disabled>` and renders a real `<a>`, which is what
 * lets `reportStoreClick()` fire at all.
 *
 * `url` is deliberately storefront-agnostic rather than the `/gb/…` URL App
 * Store Connect shows in the UI: Apple geo-redirects to the visitor's own
 * storefront, and the app ships in 175 territories, so a hardcoded `/gb/`
 * would send everyone to the UK store.
 *
 * The `/app/apple-store/id<id>` path is the exact shape App Store Connect's
 * own "Generate a Campaign Link" dialog produces, so campaign-decorated CTAs
 * are byte-identical to a link Apple generated itself.
 *
 * `appId` also unlocks a live rating badge via Apple's public iTunes Lookup API
 * (https://itunes.apple.com/lookup?id=<appId> → averageUserRating), which can
 * then replace the static proof chips in the hero.
 */
export const appStore = {
  available: true as boolean,
  url: "https://apps.apple.com/app/apple-store/id6755091280" as string | null,
  appId: "6755091280" as string | null,
};

/**
 * Play Store: mirrors `appStore` above — the Android app isn't live yet
 * either, so every "get the app" CTA that targets Android stays in the
 * non-linking "coming soon" state until `available` flips to `true` and
 * `url` is filled in.
 */
export const playStore = {
  available: false as boolean,
  url: null as string | null,
};

/**
 * Apple's Provider Token — the numeric id of our App Store Connect provider.
 * Verified 15 Aug 2026 against a link generated by App Store Connect itself
 * (Analytics → Acquisition → Campaigns → Generate a Campaign Link):
 *
 *   https://apps.apple.com/app/apple-store/id6755091280?pt=128225445&ct=<name>&mt=8
 *
 * ⚠️ `pt` is NOT a per-campaign label. It identifies the provider and is the
 * same value on every campaign link we will ever issue; the per-campaign part
 * is `ct` alone. This previously held descriptive strings (`uon_campus`,
 * `flyer_print`, `qr`), which App Analytics would not have attributed — and
 * because printed QR codes are fixed for the life of the print run, that would
 * have been unrecoverable once 5,000 leaflets shipped.
 */
export const APPLE_PROVIDER_TOKEN = "128225445";

/** Apple's media type for iOS apps; ASC includes it on every campaign link. */
const APPLE_MEDIA_TYPE = "8";

/**
 * Per-campaign attribution tokens, keyed by the landing-route slug
 * (`/uon`, `/flyer`, `/qr/:slug`). `ct` is Apple's campaign token (surfaced in
 * App Analytics); `utm_source`/`utm_campaign` are the referrer params the Play
 * Console attributes installs by. `pt` is deliberately absent — see
 * {@link APPLE_PROVIDER_TOKEN}; `appStoreUrl` supplies it. Adding a new
 * printed/QR asset is one new entry here — no other code changes. `default` is
 * the fallback used by any `/qr/:slug` whose slug isn't (yet) a distinct entry
 * of its own.
 */
export interface Campaign {
  ct?: string;
  utm_source?: string;
  utm_campaign?: string;
}

export const CAMPAIGNS: Record<string, Campaign> = {
  uon: { ct: "uon", utm_source: "uon", utm_campaign: "campus" },
  flyer: { ct: "flyer", utm_source: "flyer", utm_campaign: "print" },
  default: { ct: "qr", utm_source: "qr", utm_campaign: "qr" },
};

function appendParams(
  baseUrl: string,
  params: Record<string, string | undefined>,
): string {
  const entries = Object.entries(params).filter(
    (entry): entry is [string, string] => Boolean(entry[1]),
  );
  if (entries.length === 0) return baseUrl;
  const search = new URLSearchParams(entries);
  const separator = baseUrl.includes("?") ? "&" : "?";
  return `${baseUrl}${separator}${search.toString()}`;
}

/**
 * App Store CTA URL. With a known `campaign` slug, produces the same
 * `?pt=…&ct=…&mt=8` triple App Store Connect's own campaign-link generator
 * emits; with no campaign, returns the bare store URL. Returns `null` when the
 * store isn't live yet (`appStore.url` is `null`) — there is nothing to link to
 * regardless of campaign.
 *
 * `pt` and `mt` are constants, not per-campaign values: only `ct` varies.
 */
export function appStoreUrl(campaign?: string): string | null {
  if (!appStore.url) return null;
  if (!campaign) return appStore.url;
  const c = CAMPAIGNS[campaign];
  if (!c?.ct) return appStore.url;
  return appendParams(appStore.url, {
    pt: APPLE_PROVIDER_TOKEN,
    ct: c.ct,
    mt: APPLE_MEDIA_TYPE,
  });
}

/**
 * Play Store CTA URL — see {@link appStoreUrl}; uses `utm_source`/
 * `utm_campaign` instead of Apple's `ct`/`pt`. Returns `null` when
 * `playStore.url` is `null` (not live yet).
 */
export function playStoreUrl(campaign?: string): string | null {
  if (!playStore.url) return null;
  if (!campaign) return playStore.url;
  const c = CAMPAIGNS[campaign];
  if (!c) return playStore.url;
  return appendParams(playStore.url, {
    utm_source: c.utm_source,
    utm_campaign: c.utm_campaign,
  });
}

/**
 * Hero phone screenshot. Null → the pure-CSS app mock renders in the tilting
 * frame. When real screenshots are ready, drop the image in `public/` and set
 * this to its path (e.g. "/hero-screenshot.png", ideally a 9:19.5 portrait
 * capture) — it renders inside the same hover-tilt frame, no other changes.
 */
export const heroScreenshot: string | null = null;

/** Contact address — matches the live address used in the Privacy policy. */
export const CONTACT_EMAIL = "admin@evans-software-solutions.com";

export const TEAMS_MAILTO = `mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent(
  "Persistence for Teams",
)}`;

export const SUPPORT_MAILTO = `mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent(
  "Persistence support",
)}`;

export const COMPANY = "Evans Software Solutions Ltd";
export const COMPANY_URL = "https://evans-software-solutions.com";
