const { withPodfile } = require("@expo/config-plugins");

const MARKER = "# @generated by withExpoSQLiteHeader";
const POST_INSTALL_PATTERN =
  /(\n    react_native_post_install\([\s\S]*?\n    \)\n)/;
const FIX = `
    ${MARKER}
    # Xcode 26 can resolve the system sqlite3.h from ExpoSQLite's generated
    # umbrella header. Qualify the import so Swift sees Expo's renamed symbols.
    expo_sqlite_umbrella = installer.sandbox.root + 'Target Support Files/ExpoSQLite/ExpoSQLite-umbrella.h'
    if File.exist?(expo_sqlite_umbrella)
      contents = File.read(expo_sqlite_umbrella)
      File.write(
        expo_sqlite_umbrella,
        contents.sub('#import "sqlite3.h"', '#import <ExpoSQLite/sqlite3.h>'),
      )
    end
`;

function patchPodfile(contents) {
  if (contents.includes(MARKER)) return contents;
  if (!POST_INSTALL_PATTERN.test(contents)) {
    throw new Error(
      "Unable to add the ExpoSQLite Xcode 26 header fix: react_native_post_install was not found",
    );
  }
  return contents.replace(POST_INSTALL_PATTERN, `$1${FIX}`);
}

function withExpoSQLiteHeader(config) {
  return withPodfile(config, (podfileConfig) => {
    podfileConfig.modResults.contents = patchPodfile(
      podfileConfig.modResults.contents,
    );
    return podfileConfig;
  });
}

module.exports = withExpoSQLiteHeader;
module.exports.patchPodfile = patchPodfile;
