/* global describe, expect, it */

const { patchPodfile } = require("../withExpoSQLiteHeader");

const PODFILE = `target 'Persistence' do
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end
`;

describe("withExpoSQLiteHeader", () => {
  it("qualifies ExpoSQLite's generated sqlite header in post_install", () => {
    const result = patchPodfile(PODFILE);

    expect(result).toContain("# @generated by withExpoSQLiteHeader");
    expect(result).toContain(
      `contents.sub('#import "sqlite3.h"', '#import <ExpoSQLite/sqlite3.h>')`,
    );
    expect(result.indexOf("react_native_post_install")).toBeLessThan(
      result.indexOf("expo_sqlite_umbrella"),
    );
  });

  it("is idempotent", () => {
    const once = patchPodfile(PODFILE);
    expect(patchPodfile(once)).toBe(once);
  });

  it("fails loudly if Expo changes the generated Podfile shape", () => {
    expect(() => patchPodfile("target 'Persistence' do\nend\n")).toThrow(
      "react_native_post_install was not found",
    );
  });
});
