name: Destroy PR Environment

on:
  pull_request:
    types: [closed, unlabeled]

env:
  PR_PREFIX: pr-${{ github.event.pull_request.number }}

permissions:
  id-token: write
  contents: read

jobs:
  remove:
    name: Remove PR Environment
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' || (github.event.action == 'unlabeled' && github.event.label.name == 'ready-for-test') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_PR }}
          aws-region: ${{ vars.AWS_REGION || 'eu-west-2' }}

      - name: Remove PR Environment
        run: bunx sst remove --stage ${{ env.PR_PREFIX }}
